accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from accounts import views

urlpatterns = [
    url(r'^send_login_email$', views.send_login_email, name='send_login_email'),        
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/lib/urls.py
import re

def extract_URLs(text):
    pattern = r'(?:(?:(?:https?|ftp)://))?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!|%\$&\'\(\)\*\+,;=.]+'
    regexp = re.compile(pattern)
    return regexp.findall(text)

def URL_2_tagged_link(text, url):
    url_encoded = url.replace('?', '%3F')
    text_encoded = text.replace(url, url_encoded)
    ahref = '<a target="_blank" href="{0}">{1}</a>'.format(url_encoded, url)
    return re.sub(url_encoded, ahref, text_encoded)

def URL_tagged_text(text):
    urls = extract_URLs(text)
    for url in urls:
        text = URL_2_tagged_link(text, url)
    return text

lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import url, include
from lists import views as list_views
from lists import urls as list_urls
from accounts import urls as accounts_urls

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include('lists.urls')),
    url(r'^accounts/', include(accounts_urls)),
]

accounts/models.py
import uuid
from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.conf import settings

from lists.lib import urls

class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('view_list', args=[self.list.id])

    def get_tagged(self):
        return urls.URL_tagged_text(self.text)

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item, List

EMPTY_LIST_ERROR = "Element listy nie może być pusty!" 
DUPLICATE_ITEM_ERROR = "Ten element znajduje się już na liście"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
            'placeholder': 'Wpisz rzecz do zrobienia',
            'class': 'form-control input-lg',
            'data-toggle': 'tooltip',
            'data-placement': 'bottom',
            'title': 'Wypełnij to pole',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_LIST_ERROR }
        }

class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.shortcuts import redirect
from django.contrib import auth

from accounts.models import Token
from accounts.lib.utils import validate_email, send_link_in_message, UserMessage

def send_login_email(request):
    send_status = False
    email = request.POST['email'].lower()
    if validate_email(email):
        token = Token.objects.create(email=email)
        try:
            send_status = send_link_in_message(request, token.uid, email)
        except:
            pass
    UserMessage(request, send_status)
    return redirect('/')

def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import get_user_model

from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from lists.models import List

User = get_user_model()

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})

def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})

def view_list(request, list_id):
    list_ = get_object_or_404(List, id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})

def my_lists(request, email):
    owner = get_object_or_404(User, email=email)
    return render(request, 'my_lists.html', {'owner': owner})

accounts/templates/403_csrf.html
{% extends 'base.html' %}
{% block header-text %}Błąd 403: nieudana weryfikacja CSRF. Żądanie odrzucone.{% endblock %}
{% block list_form %}{% endblock %}
{% block extra_content %}
            <h2>Namieszałeś w kuchni i ciasteczka spalone...</h2>
            <p class="text-center">Usuń swoje ciasteczka z przeglądarki dla tej strony i zaloguj się ponownie lub powróć do strony <a href="/">głównej</a>.</p>
{% endblock %}

lists/templates/403_csrf.html
{% extends 'base.html' %}
{% block header-text %}Błąd 403: nieudana weryfikacja CSRF. Żądanie odrzucone.{% endblock %}
{% block list_form %}{% endblock %}
{% block extra_content %}
            <h2>Namieszałeś w kuchni i ciasteczka spalone...</h2>
            <p class="text-center">Usuń swoje ciasteczka z przeglądarki dla tej strony i zaloguj się ponownie lub powróć do strony <a href="/">głównej</a>.</p>
{% endblock %}

lists/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listy rzeczy do zrobienia</title>
    <link href="/static/lists/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="/static/lists/base.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="/static/lists/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" data-toggle="tooltip" data-placement="bottom" title="Wróć do strony głównej">Twoje Listy</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            {% if user.email %}
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'my_lists' user.email %}" data-toggle="tooltip" data-placement="bottom" title="Wykaz utworzonych list">Moje Listy</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="navbar-text"><span class="glyphicon glyphicon-user"></span> {{ user.email }}</li>
                <li>
                    <a href="{% url 'logout' %}" data-toggle="tooltip" data-placement="bottom" title="Wyloguj">
                        <span class="glyphicon glyphicon-log-out"></span> Wyloguj
                    </a>
                <li>
            </ul>
            {% else %}
            <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
                <span>Podaj adres email do zalogowania:</span>
                <div class="input-group">
                    <input class="form-control" name="email" type="text" data-toggle="tooltip" data-placement="bottom" title="Podaj adres email"/>
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit" data-toggle="tooltip" data-placement="bottom" title="Zaloguj">
                            <i class="glyphicon glyphicon-log-in"></i>
                        </button>
                    </div>
                </div>
                {% csrf_token %}
            </form>
            {% endif %}
        </div>
    </div>
</nav>
<div class="jumbotron">
    <div class="row">
        <div class="text-center col-md-6 col-md-offset-3" >
            <h1>{% block header-text %}{% endblock %}</h1>
            {% block list_form %}
            <form method="POST" action="{% block form-action %}{% endblock %}" novalidate>
                {{ form.text }}
                {% csrf_token %}
                {% if form.errors %}
                <div class="form-group has-error">
                    <span class="help-block">{{ form.text.errors }}</span>
                </div>
                {% endif %}
            </form>
            {% endblock %}
        </div>
    </div>
</div>
<div class="container">
    {% if messages %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
          {% for message in messages %}
            {% if message.level_tag == 'success' %}
            <div class="alert alert-success alert-dismissible fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
            {% else %}
            <div class="alert alert-warning alert-dismissible fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
            {% endif %}
          {% endfor %}
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
             {% block extra_content %}
             {% endblock %}
        </div>
    </div>
</div>
<script src="/static/lists/list.js"></script>
<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
  window.Superlists.initialize();
  window.Superlists.filter_list();
});
</script>
</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header-text %}Utwórz nową listę rzeczy do zrobienia{% endblock %}
{% block form-action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header-text %}Twoja lista rzeczy do zrobienia{% endblock %}
{% block form-action %}{% url 'view_list' list.id %}{% endblock %}
{% block table %}
    <table id="id_list_table" class="table table-hover">
	{% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}: {% autoescape off %}{{ item.get_tagged }}{% endautoescape %}</td></tr>
	{% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}
{% block header-text %}Moje Listy{% endblock %}
{% block list_form %}{% endblock %}
{% block extra_content %}
            <h2>Listy utworzone przez: {{ owner.email }}</h2>
            <ul class="my-lists">
            {% for list in owner.list_set.all %}
                <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
            {% endfor %}
            </ul>
{% endblock %}